AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  customer-app

  Sample SAM Template for customer-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.9
    Timeout: 3
    MemorySize: 128
    Environment:
      Variables:
        CUSTOMERS_TABLE: !Ref CustomersTable

Resources:
  CustomersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  CreateCustomerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: customer_app/
      Handler: create.lambda_handler
      
      Architectures:
        - x86_64
      Events:
        CreateCustomers:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /create
            Method: post
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref CustomersTable
  ReadCustomerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: customer_app/
      Handler: read.lambda_handler
      
      Architectures:
        - x86_64
      Events:
        ReadCustomers:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /read/{id}
            Method: get
      Policies: 
        - DynamoDBReadPolicy:
            TableName: !Ref CustomersTable

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CreateCustomersApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create/"
  CreateCustomerFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt CreateCustomerFunction.Arn
  CreateCustomerFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt CreateCustomerFunctionRole.Arn
